name: API Cron
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  cron:
    name: API Cron
    runs-on: ubuntu-latest

    steps:
      - name: cron
        run: |
          curl --request GET \
          --url 'https://wira-virgin-active-watch.vercel.app/api/check-watch' 